import type { Metadata } from 'next';
import Link from 'next/link';
import JsonLd from '@/components/JsonLd';
import { createArticleJsonLd, createDatasetJsonLd, createFaqJsonLd } from '@/lib/jsonLd';

export const metadata: Metadata = {
  title: 'Data Sources | Average Size Calculator',
  description:
    'Review the data sources used by Average Size Calculator, including global average size references, country comparison data, percentile assumptions, and methodology limitations.'
};

const faqItems = [
  ['What data sources does Average Size Calculator use?', 'The site uses published global reference data, compiled country comparison data for erect length, and statistical assumptions for percentile and z-score estimates.'],
  ['Where do the global average size numbers come from?', 'The global references come from the Veale et al. 2015 systematic review, which is used as the primary baseline for broad comparison.'],
  ['Where does the country comparison data come from?', 'Country comparison values come from the WorldData.info country ranking source used for average erect length by country.'],
  ['Why is country data less reliable than global data?', 'Country rankings can mix sample designs, methods, and time periods, which makes them useful context but less stable than global research references.'],
  ['Does the site use user-submitted measurements as data?', 'No. User-entered values are not converted into a source dataset to create new averages.'],
  ['Does the calculator store my measurement?', 'Measurements are processed in the browser for instant results and are not stored as personal source records.'],
  ['Are percentile results directly measured?', 'No. Percentiles are derived estimates calculated from global reference averages and statistical assumptions.'],
  ['Why are girth and flaccid length not listed by country?', 'The current country source used on this site provides erect length comparison, not a consistent country-level dataset for girth or flaccid length.'],
  ['Can these sources diagnose a medical condition?', 'No. These sources are educational references and do not diagnose, treat, or provide medical advice.'],
  ['Will the data sources be updated?', 'Sources may be updated when stronger references or clearer datasets are available, but no fixed timeline is promised.']
] as const;

export default function DataSourcesPage() {
  const faqJsonLd = createFaqJsonLd(faqItems.map(([q, a]) => ({ q, a })));
  const articleJsonLd = createArticleJsonLd({
    headline: 'Data Sources',
    description: 'A transparent overview of the research references, country data, statistical assumptions, and limitations used by Average Size Calculator.',
    path: '/data-sources'
  });
  const datasetJsonLd = createDatasetJsonLd({
    name: 'Average Size Calculator Data Sources',
    description: 'A transparent educational reference describing the global averages, country comparison data, and statistical assumptions used by Average Size Calculator.',
    path: '/data-sources',
    keywords: ['average penis size data', 'penis size statistics', 'global average penis size', 'country average penis size', 'percentile estimate'],
    sources: ['PubMed / Veale et al. 2015', 'WorldData.info country ranking', 'https://averagesizecalculator.site/average-penis-size-by-country']
  });

  return (
    <article className="space-y-10">

      <section className="rounded-2xl border border-slate-200 bg-slate-50 p-5">
        <h2 className="text-2xl font-semibold text-slate-900">Quick answer</h2>
        <p className="text-slate-700">This page gives a direct educational answer first, then adds context and limitations. Results and comparisons are reference-based estimates, not medical diagnosis. For practical comparison tools, use the <Link className="text-brand-700 underline" href="/penis-size-calculator">penis size calculator</Link> or the <Link className="text-brand-700 underline" href="/penis-size-percentile-calculator">percentile calculator</Link>.</p>
      </section>

      <section className="rounded-2xl border border-slate-200 bg-gradient-to-b from-white to-slate-50 p-6 sm:p-8 space-y-5">
        <h1 className="text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl">Data Sources</h1>
        <p className="max-w-4xl text-base text-slate-700 sm:text-lg">A transparent overview of the research references, country data, statistical assumptions, and limitations used by Average Size Calculator.</p>
        <div className="flex flex-wrap gap-2 text-xs sm:text-sm">{['Transparent', 'Educational', 'Source-based', 'No medical diagnosis'].map((b) => <span key={b} className="rounded-full border border-slate-300 bg-white px-3 py-1 font-medium text-slate-700">{b}</span>)}</div>
        <div className="flex flex-col gap-3 sm:flex-row sm:items-center"><Link href="/penis-size-calculator" className="rounded-md bg-blue-700 px-5 py-3 text-center font-semibold text-white hover:bg-blue-800">Use the Calculator</Link><Link href="/methodology" className="rounded-md border border-brand-300 px-5 py-3 text-center font-semibold text-brand-800 hover:bg-brand-50">Read the Methodology</Link></div>
      </section>
      <section className="space-y-3"><h2 className="text-2xl font-semibold text-slate-900">Why data sources matter</h2><p className="text-slate-700">Size calculators are only useful when the data behind them is explained clearly. Without transparent sourcing, users can confuse an educational estimate with a precise personal assessment. This page explains the site&#39;s penis size data sources so users can interpret results with context instead of certainty. It separates the data into three layers: global references, country comparison values, and derived statistical outputs.</p><p className="text-slate-700">Those layers do not have equal reliability. Global average references generally offer stronger stability. Country rankings can vary because they may combine different methods and sample types. Percentiles and z-scores are not directly observed measurements; they are calculated estimates built from assumptions. Making those distinctions explicit helps avoid false precision and supports healthier interpretation.</p><p className="text-slate-700">This approach also supports better E-E-A-T signals: the page states what is known, what is limited, and what is derived. Numbers are useful when framed honestly. They are less useful when presented without boundaries.</p></section>
      <section className="space-y-4"><h2 className="text-2xl font-semibold text-slate-900">Summary of sources used</h2><div className="overflow-auto rounded-xl border border-slate-200 bg-white"><table className="w-full text-left text-sm sm:text-base"><thead className="bg-slate-50"><tr><th className="px-4 py-3">Source</th><th className="px-4 py-3">Used for</th><th className="px-4 py-3">Data type</th><th className="px-4 py-3">Reliability note</th></tr></thead><tbody><tr className="border-t"><td className="px-4 py-3">Veale et al. 2015 systematic review</td><td className="px-4 py-3">Global averages for length, girth, and flaccid length</td><td className="px-4 py-3">Published research</td><td className="px-4 py-3">Stronger general reference</td></tr><tr className="border-t"><td className="px-4 py-3">WorldData.info country ranking</td><td className="px-4 py-3">Country average erect length comparison</td><td className="px-4 py-3">Compiled country ranking</td><td className="px-4 py-3">Secondary reference with methodology limitations</td></tr><tr className="border-t"><td className="px-4 py-3">Statistical reference assumptions</td><td className="px-4 py-3">Percentile and z-score estimates</td><td className="px-4 py-3">Derived calculations</td><td className="px-4 py-3">Educational estimate, not diagnosis</td></tr></tbody></table></div></section>
      <section className="space-y-3"><h2 className="text-2xl font-semibold text-slate-900">Global average data</h2><p className="text-slate-700">The primary baseline for average penis size data on this site is a global research reference. These values support consistent comparison across tools and reduce dependence on more variable secondary datasets. The current global reference values are:</p><ul className="list-disc pl-5 space-y-1 text-slate-700"><li>Erect length: 13.12 cm / 5.16 in</li><li>Erect girth: 11.66 cm / 4.59 in</li><li>Flaccid length: 9.16 cm / 3.61 in</li></ul><p className="text-slate-700">These values are used in the main calculator and the percentile estimator. They also support educational pages that explain <Link href="/average-penis-size" className="text-brand-700 underline font-medium">average penis size</Link> and broader interpretation rules. The global reference is generally more stable for high-level comparison than country-specific rankings. However, it is still a statistical benchmark, not an individual diagnosis.</p><p className="text-slate-700">Source link: <a href="https://pubmed.ncbi.nlm.nih.gov/25487360/" target="_blank" rel="noopener noreferrer" className="text-brand-700 underline font-medium">Veale et al. 2015 systematic review</a>.</p></section>
      <section className="space-y-3"><h2 className="text-2xl font-semibold text-slate-900">Country comparison data</h2><p className="text-slate-700">Country average comparison on this site uses WorldData.info as a compiled secondary reference. The current dataset is used for average erect length by country. It is not currently used for country-level girth or flaccid length because those values are not provided in a consistent way in the same source framework.</p><p className="text-slate-700">Country differences can reflect many factors beyond biology, including source selection, sample design, measurement protocol, publication year, and rounding behavior. For this reason, country values are useful as broad context and not as clinical standards. They help users understand distribution narratives, but they should not be interpreted as precise personal benchmarks.</p><p className="text-slate-700">Source link: <a href="https://www.worlddata.info/average-penissize.php" target="_blank" rel="noopener noreferrer" className="text-brand-700 underline font-medium">WorldData.info country ranking</a>.</p><p><Link href="/average-penis-size-by-country" className="text-brand-700 underline font-medium">See average penis size by country</Link></p></section>
      <section className="space-y-4"><h2 className="text-2xl font-semibold text-slate-900">What each source is used for</h2><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-xl border border-slate-200 bg-white p-4"><h3 className="text-lg font-semibold text-slate-900">Global average comparison</h3><p className="mt-2 text-slate-700">Uses global averages to compare length, girth, and flaccid length.</p></div><div className="rounded-xl border border-slate-200 bg-white p-4"><h3 className="text-lg font-semibold text-slate-900">Country comparison</h3><p className="mt-2 text-slate-700">Uses compiled country data only for erect length.</p></div><div className="rounded-xl border border-slate-200 bg-white p-4"><h3 className="text-lg font-semibold text-slate-900">Percentile estimate</h3><p className="mt-2 text-slate-700">Uses global average and standard deviation assumptions to estimate percentile.</p></div><div className="rounded-xl border border-slate-200 bg-white p-4"><h3 className="text-lg font-semibold text-slate-900">Z-score</h3><p className="mt-2 text-slate-700">Uses measurement, average, and standard deviation to calculate distance from the mean.</p></div></div></section>
      <section className="space-y-4"><h2 className="text-2xl font-semibold text-slate-900">How we think about reliability</h2><p className="text-slate-700">Published research is generally more reliable than informal or self-reported claims. Standardized measurement methods usually produce better comparability than mixed approaches. Compiled country datasets can still be educational, but they often include more methodological variation. Percentiles and z-scores are further derived outputs that depend on assumptions and should be interpreted as estimates rather than direct measurements.</p><div className="overflow-auto rounded-xl border border-slate-200 bg-white"><table className="w-full text-left text-sm sm:text-base"><thead className="bg-slate-50"><tr><th className="px-4 py-3">Reliability level</th><th className="px-4 py-3">Meaning</th><th className="px-4 py-3">Example</th></tr></thead><tbody><tr className="border-t"><td className="px-4 py-3">Stronger reference</td><td className="px-4 py-3">Published or more standardized research</td><td className="px-4 py-3">Global averages</td></tr><tr className="border-t"><td className="px-4 py-3">Secondary reference</td><td className="px-4 py-3">Compiled data with possible methodology variation</td><td className="px-4 py-3">Country averages</td></tr><tr className="border-t"><td className="px-4 py-3">Derived estimate</td><td className="px-4 py-3">Calculation based on assumptions</td><td className="px-4 py-3">Percentiles and z-scores</td></tr></tbody></table></div></section>
      <section className="space-y-3"><h2 className="text-2xl font-semibold text-slate-900">Why country data is less stable</h2><p className="text-slate-700">Country datasets can differ in sample size, sampling strategy, and measurement method. Some records can combine multiple studies, and some can reflect older publications with different protocols. Even small rounding changes can shift ranking positions and create exaggerated visual differences between nearby countries.</p><p className="text-slate-700">Country comparison can be interesting, but it should not be treated as more precise than the global reference data.</p></section>
      <section className="space-y-3"><h2 className="text-2xl font-semibold text-slate-900">Why user measurements are not used as source data</h2><p className="text-slate-700">This site does not convert user input into a measurement database. That protects privacy, reduces risk around sensitive data, and avoids building averages from unverified self-report. User values are calculated in the browser for educational output and not retained as source records for public statistics.</p><p className="text-slate-700">Read more in the <Link href="/privacy-policy" className="text-brand-700 underline font-medium">Privacy Policy</Link>.</p></section>
      <section className="space-y-4"><h2 className="text-2xl font-semibold text-slate-900">How sources connect to each tool</h2><div className="overflow-auto rounded-xl border border-slate-200 bg-white"><table className="w-full text-left text-sm sm:text-base"><thead className="bg-slate-50"><tr><th className="px-4 py-3">Tool or page</th><th className="px-4 py-3">Main source used</th><th className="px-4 py-3">Notes</th></tr></thead><tbody><tr className="border-t"><td className="px-4 py-3">Penis Size Calculator</td><td className="px-4 py-3">Global averages + country erect length data</td><td className="px-4 py-3">Country comparison only for erect length</td></tr><tr className="border-t"><td className="px-4 py-3">Percentile Calculator</td><td className="px-4 py-3">Global averages + statistical assumptions</td><td className="px-4 py-3">No country data</td></tr><tr className="border-t"><td className="px-4 py-3">Average Penis Size</td><td className="px-4 py-3">Global average reference</td><td className="px-4 py-3">Explains length, girth, flaccid length</td></tr><tr className="border-t"><td className="px-4 py-3">Average by Country</td><td className="px-4 py-3">WorldData.info country ranking</td><td className="px-4 py-3">Erect length only</td></tr><tr className="border-t"><td className="px-4 py-3">How to Measure</td><td className="px-4 py-3">Measurement guidance</td><td className="px-4 py-3">Helps reduce user measurement error</td></tr><tr className="border-t"><td className="px-4 py-3">Methodology</td><td className="px-4 py-3">All sources and assumptions</td><td className="px-4 py-3">Explains calculations</td></tr></tbody></table></div><p className="text-slate-700">Related pages: <Link href="/methodology" className="text-brand-700 underline font-medium">Methodology</Link>, <Link href="/penis-size-percentile-calculator" className="text-brand-700 underline font-medium">Percentile Calculator</Link>, <Link href="/how-to-measure" className="text-brand-700 underline font-medium">How to Measure</Link>, and <Link href="/is-my-penis-small" className="text-brand-700 underline font-medium">Is My Penis Small?</Link>.</p></section>
      <section className="space-y-3"><h2 className="text-2xl font-semibold text-slate-900">How to interpret your result responsibly</h2><p className="text-slate-700">When reading calculator output, start with category, not tiny decimal differences. A gap of a few millimeters is usually less important than understanding whether your value is broadly near, below, or above reference averages. Combine output from the main calculator, percentile estimator, and measurement guidance before drawing conclusions. If one result looks unusual, re-check your technique and units first. In statistics, measurement noise is common, especially with self-measurement. Responsible interpretation means using numbers as context, not identity.</p><p className="text-slate-700">If you want a deeper explanation of assumptions and formulas, visit the <Link href="/methodology" className="text-brand-700 underline font-medium">Methodology</Link> page. If your concern is emotional or health-related rather than statistical, supportive conversation with a qualified professional may be more helpful than repeated recalculation.</p></section>
      <section className="space-y-3"><h2 className="text-2xl font-semibold text-slate-900">Limitations of the data</h2><p className="text-slate-700">No dataset is perfect. Studies can include selection bias. Self-report can distort values. Measurement methodology can change outcomes. Country ranking should not be treated as definitive personal comparison. Percentiles depend on assumptions. For all of these reasons, this site is educational and does not diagnose medical conditions.</p></section>
      <section className="space-y-3"><h2 className="text-2xl font-semibold text-slate-900">Future data improvements</h2><p className="text-slate-700">Future improvements may include additional reviewed sources, clearer separation by measurement method, stronger girth references, improved documentation of standard deviation assumptions, and expanded educational pages explaining statistical terms. Sources can be refreshed when necessary, but no date commitments are made.</p></section>
      <section className="rounded-xl border border-blue-200 bg-blue-50 p-5 space-y-2"><h2 className="text-2xl font-semibold text-slate-900">Educational disclaimer</h2><p className="text-slate-800">Average Size Calculator provides educational comparisons based on available reference data. It does not provide medical advice, diagnosis, or treatment. If you have concerns about pain, development, sexual function, or health, consider speaking with a qualified healthcare professional.</p></section>
      <section className="space-y-4"><h2 className="text-2xl font-semibold text-slate-900">FAQ</h2>{faqItems.map(([q, a]) => <div key={q} className="space-y-1"><h3 className="text-lg font-semibold text-slate-900">{q}</h3><p className="text-slate-700">{a}</p></div>)}</section>
      <section className="rounded-2xl border border-slate-200 bg-white p-6 text-center space-y-2"><h2 className="text-2xl font-semibold text-slate-900">More pages</h2><p className="text-slate-700"><Link href="/average-penis-size" className="text-brand-700 underline font-medium">Average Penis Size</Link> · <Link href="/terms-of-use" className="text-brand-700 underline font-medium">Terms of Use</Link> · <Link href="/contact" className="text-brand-700 underline font-medium">Contact</Link></p></section>
      {faqJsonLd ? <JsonLd data={faqJsonLd} /> : null}
      <JsonLd data={articleJsonLd} />
      <JsonLd data={datasetJsonLd} />
    

      <section className="rounded-2xl border border-slate-200 bg-white p-5 text-sm text-slate-700">
        <h2 className="text-lg font-semibold text-slate-900">How to cite this page</h2>
        <p>Average Size Calculator. “Data Sources”. Average Size Calculator, https://averagesizecalculator.site/data-sources. Accessed 2026.</p>
      </section>

    

      <section className="rounded-2xl border border-slate-200 bg-white p-5">
        <h2 className="text-2xl font-semibold text-slate-900">Key facts</h2>
        <ul className="mt-3 list-disc space-y-1 pl-5 text-slate-700">
          <li>This page is educational and does not provide medical diagnosis.</li>
          <li>This site uses global reference data and transparent methodology.</li>
          <li>Country data is secondary context and used only for erect length where available.</li>
          <li>Percentiles are educational estimates based on statistical assumptions.</li>
          <li>Measurements are calculated in the browser and are not stored.</li>
        </ul>
      </section>

    </article>
  );
}
