import type { Metadata } from 'next';
import Link from 'next/link';
import { GLOBAL_AVERAGES_CM, GLOBAL_AVERAGE_SOURCE } from '@/data/penisSizeAverages';

export const metadata: Metadata = {
  title: 'Methodology | How Average Size Calculator Works',
  description:
    'Learn how Average Size Calculator uses global averages, country reference data, percentiles, z-scores, and measurement guidance to provide private educational comparisons.'
};

const toInches = (cm: number) => cm / 2.54;
const formatCm = (value: number) => `${value.toFixed(2)} cm`;
const formatIn = (value: number) => `${toInches(value).toFixed(2)} in`;

export default function MethodologyPage() {
  const faqItems = [
    ['How does Average Size Calculator work?', 'You enter a value, select units and measurement type, and the tool compares your value against educational reference data.'],
    ['Where do the global averages come from?', `The global references are based on ${GLOBAL_AVERAGE_SOURCE.label}, used as the primary baseline on this site.`],
    ['Does the calculator store my measurement?', 'No. Calculations are browser-based and the calculator does not store your measurement as an account profile.'],
    ['How is percentile calculated?', 'Percentile is estimated from a reference average, standard deviation, and a statistical conversion from z-score to percentile.'],
    ['What is a z-score?', 'A z-score shows how far a value is from the average in standard-deviation units.'],
    ['Why is country data less reliable than global data?', 'Country values often combine mixed data sources and methods, so they are secondary references.'],
    ['Why is country comparison only available for erect length?', 'Current country data is available for erect length and not consistently available for country-level girth or flaccid values.'],
    ['Does the calculator diagnose medical conditions?', 'No. It is an educational tool and does not diagnose, treat, or provide medical advice.'],
    ['Can incorrect measurement change the result?', 'Yes. Inconsistent measurement technique, unit errors, and rounding can change comparison and percentile outputs.'],
    ['Which calculator should I use?', 'Use the main calculator for above/below-average comparison and the percentile calculator for distribution position.']
  ] as const;

  const faqJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faqItems.map(([q, a]) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: a } }))
  };

  const articleJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: 'Methodology',
    description:
      'How Average Size Calculator uses global averages, country reference data, percentiles, z-scores, and measurement guidance to provide private educational comparisons.',
    author: { '@type': 'Organization', name: 'Average Size Calculator' },
    publisher: { '@type': 'Organization', name: 'Average Size Calculator' },
    mainEntityOfPage: 'https://averagesizecalculator.site/methodology',
    dateModified: new Date().toISOString()
  };

  return (
    <article className="space-y-10">
      <section className="rounded-2xl border border-slate-200 bg-gradient-to-b from-white to-slate-50 p-6 sm:p-8 space-y-5">
        <h1 className="text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl">Methodology</h1>
        <p className="max-w-4xl text-base text-slate-700 sm:text-lg">How Average Size Calculator uses published averages, country reference data, percentiles, z-scores, and measurement guidance to provide private educational comparisons.</p>
        <div className="flex flex-wrap gap-2 text-xs sm:text-sm">{['Transparent data', 'Private calculation', 'Educational', 'No measurement stored'].map((b) => <span key={b} className="rounded-full border border-slate-300 bg-white px-3 py-1 font-medium text-slate-700">{b}</span>)}</div>
        <div className="flex flex-col gap-3 sm:flex-row sm:items-center"><Link href="/penis-size-calculator" className="rounded-md bg-blue-700 px-5 py-3 text-center font-semibold text-white hover:bg-blue-800">Use the Penis Size Calculator</Link><Link href="/penis-size-percentile-calculator" className="rounded-md border border-brand-300 px-5 py-3 text-center font-semibold text-brand-800 hover:bg-brand-50">Try the Percentile Calculator</Link></div>
      </section>

      <section className="space-y-3"><h2 className="text-2xl font-semibold text-slate-900">What this methodology page explains</h2><p className="text-slate-700">This penis size calculator methodology page explains how the site processes measurements, selects statistical references, estimates percentile, interprets z-scores, and protects privacy. The goal is to make the process understandable before any number is interpreted. A transparent method helps users read results calmly and avoid overconfidence in single values.</p><p className="text-slate-700">Specifically, this page explains how measurements are compared, how global averages are prioritized, how country data is treated, why percentiles are estimates, and why correct measurement method matters. It also explains why outputs are educational only and should not be considered diagnosis.</p></section>

      <section className="space-y-4"><h2 className="text-2xl font-semibold text-slate-900">Global average reference data</h2><p className="text-slate-700">The main benchmark is global average penis size data from a published review. Global values are used as the primary reference because they are usually more stable for broad population comparison than mixed country-level records.</p><div className="overflow-auto rounded-xl border border-slate-200 bg-white"><table className="w-full text-left text-sm sm:text-base"><thead className="bg-slate-50"><tr><th className="px-4 py-3">Measurement type</th><th className="px-4 py-3 text-right">Global average cm</th><th className="px-4 py-3 text-right">Global average inches</th></tr></thead><tbody><tr className="border-t"><td className="px-4 py-3">Erect length</td><td className="px-4 py-3 text-right">{formatCm(GLOBAL_AVERAGES_CM.erectLength)}</td><td className="px-4 py-3 text-right">{formatIn(GLOBAL_AVERAGES_CM.erectLength)}</td></tr><tr className="border-t"><td className="px-4 py-3">Erect girth</td><td className="px-4 py-3 text-right">{formatCm(GLOBAL_AVERAGES_CM.erectGirth)}</td><td className="px-4 py-3 text-right">{formatIn(GLOBAL_AVERAGES_CM.erectGirth)}</td></tr><tr className="border-t"><td className="px-4 py-3">Flaccid length</td><td className="px-4 py-3 text-right">{formatCm(GLOBAL_AVERAGES_CM.flaccidLength)}</td><td className="px-4 py-3 text-right">{formatIn(GLOBAL_AVERAGES_CM.flaccidLength)}</td></tr></tbody></table></div><p className="text-slate-700">These averages are statistical reference points. Above or below average is not a medical diagnosis. Average values support educational comparison only, and small differences should not be overinterpreted.</p><p><Link href="/average-penis-size" className="text-brand-700 underline font-medium">Learn more about average penis size</Link></p></section>

      <section className="space-y-3"><h2 className="text-2xl font-semibold text-slate-900">How the main calculator compares measurements</h2><ol className="list-decimal pl-5 space-y-1 text-slate-700"><li>User enters a measurement.</li><li>User selects cm or inches.</li><li>User selects erect length, erect girth, or flaccid length.</li><li>User optionally selects a country.</li><li>Value is converted to centimeters internally.</li><li>Value is compared with global average.</li><li>When available, erect length is compared with country average.</li><li>Result shows differences in cm and inches.</li></ol><p className="text-slate-700">Global average is the primary comparison. Country average is secondary. Girth and flaccid length currently use only global averages. Calculation happens in the browser and no measurement is stored.</p></section>

      <section className="space-y-3"><h2 className="text-2xl font-semibold text-slate-900">How country comparison works</h2><p className="text-slate-700">Country average penis size data is available for erect length comparison only. The current country dataset comes from a public compiled source. Because country rankings can combine different methodologies, sample types, and publication periods, they should be interpreted as broad educational context rather than precise standards.</p><p className="text-slate-700">The dataset does not currently include consistent country-level erect girth or flaccid length references. As a result, those measurement types use global values only. For general interpretation, global average is usually more stable than country values.</p><p><Link href="/average-penis-size-by-country" className="text-brand-700 underline font-medium">See average penis size by country</Link></p><p className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">Country averages are useful for broad reference, but they should not be treated as precise clinical standards.</p></section>

      <section className="space-y-3"><h2 className="text-2xl font-semibold text-slate-900">How percentile is estimated</h2><p className="text-slate-700">Percentile describes position inside a reference distribution. A 50th percentile result is near the central reference point. Above 50 is above that point, and below 50 is below it. Percentile is descriptive statistics, not a quality score or diagnosis.</p><p className="text-slate-700">The penis size percentile calculation model uses global average, standard deviation, an approximate distribution assumption, and a statistical function to convert z-score to percentile probability. Because model assumptions simplify reality, percentile outputs are educational estimates.</p><p><Link href="/penis-size-percentile-calculator" className="text-brand-700 underline font-medium">Try the percentile calculator</Link></p></section>

      <section className="space-y-3 rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-2xl font-semibold text-slate-900">What is a z-score?</h2><p className="font-mono text-sm sm:text-base rounded-md bg-slate-100 px-3 py-2">z-score = (your measurement - average) / standard deviation</p><p className="text-slate-700">A z-score of 0 means close to average. A positive z-score means above average. A negative z-score means below average. The metric is used to estimate percentile consistently across different scales.</p><ul className="list-disc pl-5 space-y-1 text-slate-700"><li>A z-score near 0 means the measurement is close to the reference average.</li><li>A positive z-score means the measurement is above the reference average.</li><li>A negative z-score means the measurement is below the reference average.</li></ul><p className="text-slate-700">Z-score is a statistical estimate and not a medical diagnosis.</p></section>

      <section className="space-y-4"><h2 className="text-2xl font-semibold text-slate-900">Data used by each result</h2><div className="overflow-auto rounded-xl border border-slate-200 bg-white"><table className="w-full text-left text-sm sm:text-base"><thead className="bg-slate-50"><tr><th className="px-4 py-3">Result shown</th><th className="px-4 py-3">Data used</th><th className="px-4 py-3">Reliability note</th></tr></thead><tbody><tr className="border-t"><td className="px-4 py-3">Global average comparison</td><td className="px-4 py-3">Published global averages</td><td className="px-4 py-3">Stronger general reference</td></tr><tr className="border-t"><td className="px-4 py-3">Country comparison</td><td className="px-4 py-3">Compiled country erect length data</td><td className="px-4 py-3">Secondary reference</td></tr><tr className="border-t"><td className="px-4 py-3">Percentile estimate</td><td className="px-4 py-3">Global average and standard deviation</td><td className="px-4 py-3">Educational estimate</td></tr><tr className="border-t"><td className="px-4 py-3">Z-score</td><td className="px-4 py-3">Measurement, average, and standard deviation</td><td className="px-4 py-3">Statistical estimate</td></tr><tr className="border-t"><td className="px-4 py-3">Girth comparison</td><td className="px-4 py-3">Global average only</td><td className="px-4 py-3">No country-level girth data</td></tr><tr className="border-t"><td className="px-4 py-3">Flaccid comparison</td><td className="px-4 py-3">Global average only</td><td className="px-4 py-3">No country-level flaccid data</td></tr></tbody></table></div></section>

      <section className="space-y-3"><h2 className="text-2xl font-semibold text-slate-900">Why calculator results are estimates</h2><p className="text-slate-700">Several factors affect penis size calculator accuracy. Studies use different sampling and measurement protocols. Country datasets can be less standardized. User measurements may vary due to technique and timing. Distribution assumptions are approximate and extreme percentiles may be less precise. Small differences can be statistically visible while practically minor. The calculator is designed to provide an educational reference, not a medical classification.</p></section>
      <section className="space-y-3"><h2 className="text-2xl font-semibold text-slate-900">Why measurement accuracy matters</h2><p className="text-slate-700">Measurement error can change your result meaningfully. Length should be measured consistently from base to tip. Girth should be measured using a flexible tape with consistent tension. Centimeters and inches should not be mixed, and aggressive rounding should be avoided before calculation.</p><p className="text-slate-700">If values differ across attempts, measure several times under similar conditions and use a stable average reading. Consistent penis size measurement method improves interpretation reliability.</p><p><Link href="/how-to-measure" className="text-brand-700 underline font-medium">Learn how to measure correctly</Link></p></section>
      <section className="space-y-3"><h2 className="text-2xl font-semibold text-slate-900">Average, below average, and normal variation</h2><p className="text-slate-700">Average is a midpoint, not a pass/fail line. In natural biological variation, many people are below average and many are above it. Below average does not automatically indicate a problem, and above average does not guarantee better health outcomes. Variation is normal.</p><p className="text-slate-700">Results should be interpreted calmly and as educational context only.</p><p><Link href="/is-my-penis-small" className="text-brand-700 underline font-medium">Is My Penis Small?</Link></p></section>
      <section className="space-y-3"><h2 className="text-2xl font-semibold text-slate-900">Privacy and browser-based calculation</h2><p className="text-slate-700">No account is required. No photo upload is required. Measurements are processed in-browser for comparison and are not stored as user measurement profiles by the tool. Users can access the calculator privately and anonymously.</p><p className="text-slate-700">Please do not use contact forms to send sensitive medical information. Use policy pages to understand data handling and site usage.</p><p><Link href="/privacy-policy" className="text-brand-700 underline font-medium">Privacy Policy</Link> · <Link href="/terms-of-use" className="text-brand-700 underline font-medium">Terms of Use</Link> · <Link href="/contact" className="text-brand-700 underline font-medium">Contact</Link></p></section>
      <section className="rounded-xl border border-blue-200 bg-blue-50 p-5 space-y-2"><h2 className="text-2xl font-semibold text-slate-900">Educational disclaimer</h2><p className="text-slate-800">Average Size Calculator is for educational purposes only. It does not provide medical advice, diagnosis, or treatment. If you have concerns about pain, development, sexual function, or health, consider speaking with a qualified healthcare professional.</p></section>

      <section className="space-y-4"><h2 className="text-2xl font-semibold text-slate-900">Which tool should you use?</h2><div className="overflow-auto rounded-xl border border-slate-200 bg-white"><table className="w-full text-left text-sm sm:text-base"><thead className="bg-slate-50"><tr><th className="px-4 py-3">If you want to know...</th><th className="px-4 py-3">Use this page</th></tr></thead><tbody><tr className="border-t"><td className="px-4 py-3">Am I above or below average?</td><td className="px-4 py-3"><Link href="/penis-size-calculator" className="text-brand-700 underline">Penis size calculator</Link></td></tr><tr className="border-t"><td className="px-4 py-3">What percentile am I in?</td><td className="px-4 py-3"><Link href="/penis-size-percentile-calculator" className="text-brand-700 underline">Percentile calculator</Link></td></tr><tr className="border-t"><td className="px-4 py-3">What is average size?</td><td className="px-4 py-3"><Link href="/average-penis-size" className="text-brand-700 underline">Average penis size guide</Link></td></tr><tr className="border-t"><td className="px-4 py-3">How do countries compare?</td><td className="px-4 py-3"><Link href="/average-penis-size-by-country" className="text-brand-700 underline">Average penis size by country</Link></td></tr><tr className="border-t"><td className="px-4 py-3">How do I measure correctly?</td><td className="px-4 py-3"><Link href="/how-to-measure" className="text-brand-700 underline">How to measure correctly</Link></td></tr><tr className="border-t"><td className="px-4 py-3">Am I small or normal?</td><td className="px-4 py-3"><Link href="/is-my-penis-small" className="text-brand-700 underline">Is My Penis Small? guide</Link></td></tr></tbody></table></div></section>

      <section className="space-y-4"><h2 className="text-2xl font-semibold text-slate-900">FAQ</h2>{faqItems.map(([q, a]) => <div key={q} className="space-y-1"><h3 className="text-lg font-semibold text-slate-900">{q}</h3><p className="text-slate-700">{a}</p></div>)}</section>
      <section className="rounded-2xl border border-slate-200 bg-white p-6 text-center space-y-3"><h2 className="text-2xl font-semibold text-slate-900">Use the right calculator for your question</h2><p className="text-slate-700">Start with comparison, then use percentile for distribution context.</p><div className="flex flex-col gap-3 sm:flex-row sm:justify-center"><Link href="/penis-size-calculator" className="rounded-md bg-blue-700 px-5 py-3 font-semibold text-white hover:bg-blue-800">Use the Penis Size Calculator</Link><Link href="/penis-size-percentile-calculator" className="rounded-md border border-brand-300 px-5 py-3 font-semibold text-brand-800 hover:bg-brand-50">Try the Percentile Calculator</Link></div></section>

      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleJsonLd) }} />
    </article>
  );
}
